name: Midterm
description: Learn how to use Material for structure and layout.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  english_words: ^4.0.0
  animated_text_kit: ^4.2.1
  lottie: ^1.2.2
  url_launcher: ^6.0.20
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  provider: ^6.0.4
  firebase_ui_auth: ^1.0.4
  firebase_storage: ^11.0.4
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.webp
    - assets/hotel.png
    - assets/launcher_icon/students.png

      #Hotel image
    - assets/hotels/hotel1.jpeg
    - assets/hotels/hotel2.jpeg
    - assets/hotels/hotel3.jpg
    - assets/hotels/hotel4.jpeg
    - assets/hotels/hotel5.jpeg
    - assets/hotels/hotel6.jpeg
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 200
    - family: Cooper
      fonts:
        - asset: assets/fonts/Cooper-Regular.ttf


